from datetime import *
d=date(year=2021,month=7,day=30)
print(d)
print("Excess data by usining attributes of date class")
print(d.year)
print(d.month)
print(d.day)
print()
print("Without attribute")
d=date(2021,7,30)
print(d)
# todo date class method today()
print("using today method")
d1=date.today()
print(d1)
print("Excess data by usining attributes of date class today method")
print(d1.year)
print(d1.month)
print(d1.day)

