from datetime import *
dt=datetime.today()
print("without formmating datetime")
print(dt)
print()
print("get formatted date and time")
nd=dt.strftime("%B,%d,%Y,%a,%A,%b,%m,%Y,%y")
print(nd)
print()
print("for time only")
print(dt.strftime("%H:%M:%S"))
print()
print("for date only")
print(dt.strftime("%d/%b/%Y"))
print()
print("for date only")
print(dt.strftime("%d-%m-%Y"))
print()
print("for date only")
print(dt.strftime("%B,%d,%Y"))
print()
print("time in 12 hourse")
print(dt.strftime("%I:%M:%S"))

